dofile('client/ptt.lua')
assert(HumalikeVoicePtt.InputPressed(true, false, false, false, false, false))
assert(HumalikeVoicePtt.InputPressed(false, true, true, false, false, false))
assert(HumalikeVoicePtt.InputPressed(false, true, false, true, false, false))
assert(HumalikeVoicePtt.InputPressed(false, true, false, false, true, false))
assert(HumalikeVoicePtt.InputPressed(false, true, false, false, false, true))
assert(not HumalikeVoicePtt.InputPressed(false, true, false, false, false, false))
assert(not HumalikeVoicePtt.InputPressed(false, false, true, true, true, true))
assert(HumalikeVoicePtt.Allowed(true, false))
assert(not HumalikeVoicePtt.Allowed(true, true))
assert(not HumalikeVoicePtt.Allowed(false, false))
print('ptt: ok')
